version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - echo Path is $CODEBUILD_SRC_DIR

artifacts:
  files:
    - 'build/**/*'
    - 'appspec.yml'
    - 'scripts/*'
  name: 'react-lab-build-$(date +%Y-%m-%d)'
