version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - mv appspec.yml /build

artifacts:
  files:
    - 'build/*'
    - 'build/appspec.yml'
  name: react-lab-build-$(date +%Y-%m-%d)
